name: flutter_game_runner
description: "An endless runner Flame game example."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  flame: ^1.18.0
  flame_audio: ^2.10.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  logging: ^1.2.0
  nes_ui: ^0.20.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flame_test: ^1.16.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/dash/
    - assets/images/enemies/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/
    
  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true